apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET_KEY: GET FROM AZURE-KV
  SENDGRID_API_KEY: GET FROM AZURE-KV
  DATABASE_URL: GET FROM AZURE-KV
  DATABASE_USER: GET FROM AZURE-KV
  DATABASE_USER_PASSWORD: GET FROM AZURE-KV

