apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET_KEY: Q3dNTW9RT2RGZ080QXpIanRHdjFNVTBldCtmRnRFTVp0NFVGNE85SHJTdz0=
  SENDGRID_API_KEY: U0cuaU5kZnE3U2tUME9weHFJbS1NX3pYZy5PUi1vQXRYak1HX1Q0OGtFWU5iQ1RobXJDRXB6REx2ZTN3MlRLSGRNdENv
