apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET_KEY: Q3dNTW9RT2RGZ080QXpIanRHdjFNVTBldCtmRnRFTVp0NFVGNE85SHJTdz0=
  SENDGRID_API_KEY: U0cuQWtSWTR2X2xRR1dPUlVaZVlBVzJVZy56SHplc3dyTF9NWk1XU01XSndTcS1KLVJnSmI2RldFNDRzbFRJYm9zbnU0
