name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push frontend image
      run: |
        docker buildx build --platform linux/amd64 -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend:latest --push ./frontend

    - name: Build and push backend image
      run: |
        docker buildx build --platform linux/amd64 -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/backend:latest --push ./backend

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.26.0'

    - name: Get AKS context
      uses: azure/aks-set-context@v2
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Deploy ConfigMap to AKS
      run: |
        kubectl apply -f k8s/configmap.yaml

    - name: Deploy frontend to AKS
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml --validate=false
        kubectl delete pod -l app=frontend

    - name: Deploy frontend service to AKS
      run: |
        kubectl apply -f k8s/frontend-service.yaml

    - name: Deploy ingress to AKS
      run: |
        kubectl apply -f k8s/ingress.yaml

    - name: Deploy backend to AKS
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl delete pod -l app=backend

    - name: Deploy backend service to AKS
      run: |
        kubectl apply -f k8s/backend-service.yaml
        kubectl delete pod -l app=backend
